format = """
$cmd_duration\
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$sudo\
$fill\
$custom\
$line_break\
$jobs\
$character"""

[fill]
symbol = " "

[directory.substitutions]
"System.Security.Cryptography" = "S….S….Cryptography"

[cmd_duration]
format = '''took [$duration](bold yellow)
'''
